### ISSUE TITLE
SyntaxError: invalid syntax on windows

### ISSUE THREAD

**Issue by 0xtbug** [l4tt/uscan#1]
Hi, I found this error when I run these tools on windows 10 and WSL

``File "Uscan.py", line 36
    match input(f'[ {Colors.RED}{Colors.UNDERLINE}{Colors.BRIGHT}$can{Colors.WHITE}{Colors.RESET} ] {Colors.BRIGHT}>>{Colors.WHITE} '):
          ^
SyntaxError: invalid syntax``

![error](https://user-images.githubusercontent.com/54710482/172362230-e12247a1-d70b-4b2c-ab21-ea685ced1ea3.PNG)

**Comment by l4tt** [comment]
Probably you have to update python3
, The current version of python i'm using is 3.9, also this supports windows so instead of using WSL just install python natively.

**Comment by l4tt** [comment]
3.10 python3, for match case

**Comment by manhcot** [comment]
bro but module 'readline' not support for windows
