### ISSUE TITLE
Traceback (most recent call last):   File "/home/ea/uscan/Uscan.py", line 1, in <module>     from pytermgui import tim ModuleNotFoundError: No module named 'pytermgui'

### ISSUE THREAD

**Issue by 0x2eren** [l4tt/uscan#6]
Traceback (most recent call last):
  File "/home/ea/uscan/Uscan.py", line 1, in <module>
    from pytermgui import tim
ModuleNotFoundError: No module named 'pytermgui'

**Comment by anasghamdi** [comment]
pip3 install pytermgui
